/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AdmissionApplication = IDL.Record({
  'id' : IDL.Text,
  'status' : ApplicationStatus,
  'documentUrls' : IDL.Vec(IDL.Text),
  'studentName' : IDL.Text,
  'previousSchool' : IDL.Text,
  'dateOfBirth' : IDL.Text,
  'motherName' : IDL.Text,
  'email' : IDL.Text,
  'fatherName' : IDL.Text,
  'address' : IDL.Text,
  'timestamp' : IDL.Int,
  'mobile' : IDL.Text,
  'className' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const SubjectMark = IDL.Record({
  'marks' : IDL.Nat,
  'subject' : IDL.Text,
});
export const StudentResult = IDL.Record({
  'totalMarks' : IDL.Nat,
  'studentName' : IDL.Text,
  'subjects' : IDL.Vec(SubjectMark),
  'rollNumber' : IDL.Nat,
  'timestamp' : IDL.Int,
  'className' : IDL.Text,
  'percentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Principal], [], []),
  'getAdmissionApplication' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AdmissionApplication)],
      ['query'],
    ),
  'getAllAdmissionApplications' : IDL.Func(
      [],
      [IDL.Vec(AdmissionApplication)],
      ['query'],
    ),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllStudentResults' : IDL.Func([], [IDL.Vec(StudentResult)], ['query']),
  'getStudentResult' : IDL.Func([IDL.Nat], [IDL.Opt(StudentResult)], ['query']),
  'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'removeAdmin' : IDL.Func([IDL.Principal], [], []),
  'resetSystem' : IDL.Func([IDL.Principal], [], []),
  'submitAdmissionApplication' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitStudentResult' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(SubjectMark)],
      [],
      [],
    ),
  'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AdmissionApplication = IDL.Record({
    'id' : IDL.Text,
    'status' : ApplicationStatus,
    'documentUrls' : IDL.Vec(IDL.Text),
    'studentName' : IDL.Text,
    'previousSchool' : IDL.Text,
    'dateOfBirth' : IDL.Text,
    'motherName' : IDL.Text,
    'email' : IDL.Text,
    'fatherName' : IDL.Text,
    'address' : IDL.Text,
    'timestamp' : IDL.Int,
    'mobile' : IDL.Text,
    'className' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const SubjectMark = IDL.Record({ 'marks' : IDL.Nat, 'subject' : IDL.Text });
  const StudentResult = IDL.Record({
    'totalMarks' : IDL.Nat,
    'studentName' : IDL.Text,
    'subjects' : IDL.Vec(SubjectMark),
    'rollNumber' : IDL.Nat,
    'timestamp' : IDL.Int,
    'className' : IDL.Text,
    'percentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Principal], [], []),
    'getAdmissionApplication' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AdmissionApplication)],
        ['query'],
      ),
    'getAllAdmissionApplications' : IDL.Func(
        [],
        [IDL.Vec(AdmissionApplication)],
        ['query'],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllStudentResults' : IDL.Func([], [IDL.Vec(StudentResult)], ['query']),
    'getStudentResult' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(StudentResult)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'removeAdmin' : IDL.Func([IDL.Principal], [], []),
    'resetSystem' : IDL.Func([IDL.Principal], [], []),
    'submitAdmissionApplication' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitStudentResult' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Vec(SubjectMark)],
        [],
        [],
      ),
    'updateApplicationStatus' : IDL.Func([IDL.Text, ApplicationStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };