/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionApplication {
  'id' : string,
  'status' : ApplicationStatus,
  'documentUrls' : Array<string>,
  'studentName' : string,
  'previousSchool' : string,
  'dateOfBirth' : string,
  'motherName' : string,
  'email' : string,
  'fatherName' : string,
  'address' : string,
  'timestamp' : bigint,
  'mobile' : string,
  'className' : string,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ContactSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface StudentResult {
  'totalMarks' : bigint,
  'studentName' : string,
  'subjects' : Array<SubjectMark>,
  'rollNumber' : bigint,
  'timestamp' : bigint,
  'className' : string,
  'percentage' : bigint,
}
export interface SubjectMark { 'marks' : bigint, 'subject' : string }
export interface _SERVICE {
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'deleteAdmissionApplication' : ActorMethod<[string], undefined>,
  'deleteStudentResult' : ActorMethod<[bigint], undefined>,
  'getAdmissionApplication' : ActorMethod<
    [string],
    [] | [AdmissionApplication]
  >,
  'getAdmissionApplicationsByStatus' : ActorMethod<
    [ApplicationStatus],
    Array<AdmissionApplication>
  >,
  'getAllAdmins' : ActorMethod<[], Array<Principal>>,
  'getAllAdmissionApplications' : ActorMethod<[], Array<AdmissionApplication>>,
  'getAllApplicationsSortedByTimestamp' : ActorMethod<
    [],
    Array<AdmissionApplication>
  >,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllResultsSortedByPercentage' : ActorMethod<[], Array<StudentResult>>,
  'getAllStudentResults' : ActorMethod<[], Array<StudentResult>>,
  'getStudentResult' : ActorMethod<[bigint], [] | [StudentResult]>,
  'getStudentResultsByClass' : ActorMethod<[string], Array<StudentResult>>,
  'getStudentResultsBySubject' : ActorMethod<[string], Array<StudentResult>>,
  'initializeFirstAdmin' : ActorMethod<[], boolean>,
  'isAdmin' : ActorMethod<[Principal], boolean>,
  'isSuperAdmin' : ActorMethod<[Principal], boolean>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'removeAdminBySuperAdmin' : ActorMethod<[Principal], undefined>,
  'resetSystem' : ActorMethod<[Principal], undefined>,
  'searchApplicationsByStudentName' : ActorMethod<
    [string],
    Array<AdmissionApplication>
  >,
  'submitAdmissionApplication' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
    ],
    undefined
  >,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'submitStudentResult' : ActorMethod<
    [bigint, string, string, Array<SubjectMark>],
    undefined
  >,
  'updateApplicationDocumentUrls' : ActorMethod<
    [string, Array<string>],
    undefined
  >,
  'updateApplicationField' : ActorMethod<[string, string, string], undefined>,
  'updateApplicationStatus' : ActorMethod<
    [string, ApplicationStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];